<html>
  <head>
    <title>FREE Unique Article Creator Online</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />	
	<meta name="robots" content="noindex, nofollow" />
	<link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" media="screen" />
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/bootstrap-tooltip.js"></script>
	<script type="text/javascript" src="js/bootstrap-popover.js"></script>
	<script type="text/javascript" src="js/bootstrap-tab.js"></script>
	<style>
	html, body { background-color: #cad2d7;}
	body {
	margin: 0;
	line-height: 1.4em;
	font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;

}
	label, input, select, textarea { font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; }
	li { color: #404040; }
	li.active a { font-weight: bold; color: #666 !important; }
	form .controls { margin-left: 220px !important; }
	label { width: 200px !important; }
	fieldset legend {
	padding-left: 220px;
	line-height: 20px !important;
	margin-bottom: 0px !important;
}
	.form-actions { padding-left: 220px !important; }
	.popover-inner { width: 205px; }
	h1 {
	margin-bottom: 4px;
}
	body,td,th {
	font-family: Arial, Helvetica, sans-serif;
}
    .style1 {font-family: "Times New Roman", Times, serif}
    </style>
 </head>
  <body>
	<div class="container" style="width: 600px; border: 2px; border-radius: 0px; background-color: #FFFFFF; padding: 30px; margin-top: 30px; margin-bottom: 50px;">

	<center>
	  <div align="center" style="margin-bottom:10px;"><a href="index.php" title="FREE Unique Article Creator Online"><img src="images/ArticleCreatorLogo.png"></a></div>
	  <div style="font-size:14px; color:grey;">Automatic generate high quality seo friendly articles from your keyword</div><br /><br />
	</center>